#!/bin/bash

#
# Script um die Samba AD DC Domain aufzubauen
# Siehe auch:
# http://wiki.samba.org/index.php/Samba_AD_DC_HOWTO
#

# Todo:
# Variablen aus config nehmen
# Passwort abfragen
# Logfile ändern
# Verhalten bei Fehlern


## Variablen, ggf. aus der config oder sine uebernehmen

# "realm" bei AD DC = "Domain" im sine
# ad_realm=`getconfdata "Domain" "2"`
ad_realm="invis-net.loc"

# "domain" bei AD DC = "Workgroup" im sine
# ad_domain=`getconfdata "Workgroup" "2"`
ad_domain="INVIS-NET"

# ad_ip=`getconfdata "IP" "2"`
ad_ip="192.168.240.218" 

# Passwort vorher abfragen!
ad_adminpass="P4ssw0rd*"

# Bisher nur dc unterstuezt
ad_server_role="dc"

# Domain Function level
# --function-level="2003"
# Default: 2003, moeglich 2008, 2008_r2. Wir verwenden den aktuellen Default und lassen es weg

# Fuer UNIX UID/GID RFC2307 aktiv
# --use-rfc2307

# logfile=$setupdir/sine.log
logfile=$0.log

## ####################################################


# Domain aufbauen
samba-tool domain provision --realm="$ad_realm" --domain="$ad_domain" --host-ip="$ad_ip" --adminpass="$ad_adminpass" --server-role="$ad_server_role" --use-rfc2307 2>&1 | tee -a $logfile
provresult=${PIPESTATUS[0]}

if [[ $provresult != 0 ]]; then
  echo "Provisioning meldet Fehler $provresult! Script wird beendet!"
  exit $provresult
fi

cp /var/lib/samba/private/krb5.conf /etc/krb5.conf
